### ISSUE TITLE
postcss-px-to-viewport插件的使用

### ISSUE THREAD

**Issue by rehack** [whidy/mobileweb#2]
看了{`再聊移动端页面的适配`}这篇文章，里面提到了postcss-px-to-viewport这个插件，研究了半天也不知道怎么在webpack下配置和使用， 请教下@whidy 该如何操作？

**Comment by whidy** [comment]
@codesboy 我试了下，使用这个插件跟PostCSS其他插件无异。
webpack下只要加入postcss-loader即可，**webpack.config.js**代码片段如下：
```
rules: [
  {
    test: /\.css$/,
    exclude: /node_modules/,
    use: ExtractTextPlugin.extract({
      fallback: "style-loader",
      use: [{
        loader: 'css-loader',
        options: {
          importLoaders: 1,
        }
      }, {
        loader: 'postcss-loader'
      }]
    })
  },
  {
    ...
  }
]
```
postcss.config.js
```
require('postcss-px-to-viewport')({
  viewportWidth: 750,
  viewportHeight: 1334,
  unitPrecision: 5,
  viewportUnit: 'vw',
  selectorBlackList: [],
  minPixelValue: 1,
  mediaQuery: false
}),
...
```

参考插件说明：[postcss-px-to-viewport官方文档](https://github.com/evrone/postcss-px-to-viewport)
我在我这个项目开了个分支[postcss-px-to-viewport-test](https://github.com/whidy/mobileweb/tree/postcss-px-to-viewport-test)可以参考下。
